# Generated by Django 5.2.3 on 2025-07-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the game group", max_length=191, unique=True
                    ),
                ),
                (
                    "is_canon",
                    models.BooleanField(
                        help_text="Whether or not the game should count towards Completion"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Free-form HTML text about the game"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rom", models.FileField(max_length=255, upload_to="")),
                ("image", models.ImageField(max_length=255, upload_to="")),
                ("name", models.CharField(max_length=255)),
                ("alt", models.CharField(max_length=255)),
                ("aka", models.CharField(max_length=255)),
                ("beta", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("mfg", models.CharField(max_length=255)),
                ("serial", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("controller", models.CharField(max_length=255)),
                ("comp", models.CharField(max_length=255)),
                ("disam", models.CharField(max_length=255)),
                ("multi", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("note", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "game",
                        "name",
                        "alt",
                        "aka",
                        "beta",
                        "year",
                        "mfg",
                        "region",
                        "controller",
                        "comp",
                        "disam",
                        "multi",
                    )
                },
            },
        ),
        migrations.AddField(
            model_name="game",
            name="primary",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary Release associated with this Game",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary",
                to="games.release",
            ),
        ),
    ]
