# Generated by Django 5.2.3 on 2025-07-08 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="The auth.User model this profile is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Picture of the user",
                        max_length=255,
                        null=True,
                        upload_to="user_profiles/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A short biography about the user",
                        max_length=500,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text='Custom location field, e.g. "USA" or "London"',
                        max_length=50,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="User's birthday", null=True
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-user__is_superuser",
                    "-user__is_staff",
                    "user__username",
                ],
            },
        ),
    ]
